# .github/workflows/ci.yml
# <<08-JUN-2025:01:14>> - Basic CI: Python + Playwright + pytest.

name: CI

on:
  push:
    branches: [ main, "**" ]      # run on every branch push
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]  # add 3.12/3.13 when ready

    steps:
      - name: ⬇️  Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: 📦 Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: 🎭 Install Playwright browsers
        run: python -m playwright install --with-deps chromium

      - name: ✅ Run pytest
        env:
          HEADLESS_MODE: "true"          # ensure headless in CI
        run: |
          PYTHONPATH=$PWD pytest -q

